# Use the official Python image from the Docker Hub
FROM python:3.11

# Set the working directory in the container
WORKDIR /app

# Copy the requirements files
COPY requirements/linux-requirements.txt ./requirements/

# Install Python dependencies
RUN pip install -r requirements/linux-requirements.txt

# Copy the rest of the application code to the working directory
COPY workspace/ .

# Expose the ports the app runs on (Flask and TensorBoard)
EXPOSE 80
EXPOSE 6006

# Define the command to run the application
CMD ["python", "app.py"]
